SELECT
P.PEDIDOID as PEDIDO,
FORMAT(P.DATAINCLUSAO,'yyyyMMdd','pt-BR') DATA,
COUNT(P.QNT) PARES,
'FILA' SITUACAO,
P.RASTREAMENTO_DATA_ATUALIZACAO AS DATA_INTEGRACAO,
P.MENSAGEMERP OBSERVACAO
FROM
PULSEBD.dbo.INTM_PEDIDOS P
WHERE
ISNULL(PEDIDOERP,'')= '' 
AND FORMAT(P.DATAINCLUSAO,'yyyyMMdd','pt-BR') >= '20230529'
AND FORMAT(P.DATAINCLUSAO,'yyyyMMdd','pt-BR') < FORMAT(GETDATE(),'yyyyMMdd','pt-BR')
GROUP BY 
FORMAT(P.DATAINCLUSAO,'yyyyMMdd','pt-BR'),
P.PEDIDOID,
P.MENSAGEMERP,
P.RASTREAMENTO_DATA_ATUALIZACAO
ORDER BY 
DATA ASC