CREATE TABLE DVT_SFT_PEDIDOS_PROCESSADOS
(
	ID INT IDENTITY PRIMARY KEY,
	ID_PEDIDO VARCHAR(50),
	NUMERO_PEDIDO VARCHAR(50),
	DATA_INCLUSAO DATETIME DEFAULT GETDATE()
)

ALTER TABLE DVT_SFT_PEDIDOS_PROCESSADOS
ADD EMAIL_ENVIADO BIT DEFAULT 0;

INSERT INTO DVT_SFT_PEDIDOS_PROCESSADOS (ID_PEDIDO, NUMERO_PEDIDO)
SELECT 'TESTE', 'TESTE'

CREATE VIEW VW_DVT_SFT_PEDIDOS_PROCESSADOS AS
SELECT
	DISTINCT
	ID_PEDIDO,
	NUMERO_PEDIDO,
	DATA_INCLUSAO
FROM DVT_SFT_PEDIDOS_PROCESSADOS
WHERE EMAIL_ENVIADO = 0


UPDATE DVT_SFT_PEDIDOS_PROCESSADOS 
SET EMAIL_ENVIADO = 1 
WHERE ID_PEDIDO = '1';