SELECT C5_NUM, D_E_L_E_T_  FROM SC5100
WHERE C5_NUM IN ('QDPUT7','QDPUT9','QDPUTB','QDPUTD','QDPUTF')

SELECT C6_NUM, C6_BLQ  FROM SC6100
WHERE C6_NUM IN ('QDPUT7','QDPUT9','QDPUTB','QDPUTD','QDPUTF')